aws:
  regions:
    - eu-north-1
    - eu-west-1
    - eu-central-1
    - us-east-1
    - us-west-2
    - ap-northeast-1
    - ap-southeast-1
  instance_type: t3.small
  ami_mapping:
    eu-north-1: ami-08eb150f611ca277f
    eu-west-1: ami-0d64bb532e0502c46
    eu-central-1: ami-0084a47cc718c111a
    us-east-1: ami-0866a3c8686eaeeba
    us-west-2: ami-04dd23e62ed049936
    ap-northeast-1: ami-0b20f552f63953f0e
    ap-southeast-1: ami-047126e50991d067b
  key_pair_name: latency-test-key
  private_key_path: /home/user/exchange_latency_explorer/latency_test.pem
  access_key: XXXXX
  secret_key: XXXXX
exchanges:
  api_keys:
    binance:
      api_key: XXXXX
      secret: XXXXX
    deribit:
      api_key: XXXXX
      secret: XXXXX
output_dir: ./results
